### ISSUE TITLE
kernel 3.0 module acpi_call not found

### ISSUE THREAD

**Issue by Gravemind** [mkottman/acpi_call#11]
Hello,

Archlinux
kernel 3.0 (core)
acpi_call-git (aur)

```
$> sudo modprobe acpi_call
FATAL: Module acpi_call not found.
```

(And LOAD MODULES [FAIL] at boot)

I can load the module with `make; sudo make load` manualy from the git: acpi_call is in `lsmod` and `test_off.sh` works, but modprobe still not found the module.

Thanks.

**Comment by svanheulen** [comment]
I'm having the same problem and I'm sure it's just something that needs to be fixed in the PKGBUILD on AUR. As for installing it manually from git, you need to install it in /lib/modules/3.0-ARCH/kernel/drivers/acpi/ and run depmod -a before modprobe will find it.

**Comment by Gravemind** [comment]
fixed on archlinux/aur, thank you.
