### ISSUE TITLE
It hangs up the computer in Ubuntu 11.10 beta1

### ISSUE THREAD

**Issue by lobo-tuerto** [mkottman/acpi_call#12]
After a couple of seconds (or maybe 1 or 2 mins) the computer freezes out and doesn't recover.
Just git pulled, ran make, then inserted the module and then did: sudo insmod acpi_call.ko

This is in an Alienware m11x-R2

$ lsb_release -rd
Description:    Ubuntu oneiric (development branch)
Release:    11.10

$ uname -a
Linux tezcatlipoca 3.0.0-10-generic #16-Ubuntu SMP Fri Sep 2 18:32:04 UTC 2011 x86_64 x86_64 x86_64 GNU/Linux

**Comment by mkottman** [comment]
Restating what I wrote in issue #14, there is no warranty that calling one of the ACPI methods, or even loading it into the kernel will work. There is a script called `m11xr2.sh` in the repo, but if you cannot load the module, you unfortunately won't be able to use it. I do not have the hardware nor the time to debug the issue.
