### ISSUE TITLE
test_off.sh just sits there and does nothing

### ISSUE THREAD

**Issue by rick2047** [mkottman/acpi_call#14]
I cloned from git then

rick@Abigail:~/acpi_call$ ls
acpi_call.c   m11xr2.sh  query_dsdt.pl  test_off.sh
asus1215n.sh  Makefile   README         windump_hack
rick@Abigail:~/acpi_call$ make
make -C /lib/modules/3.0.0-0300-generic/build M=/home/rick/acpi_call modules
make[1]: Entering directory `/usr/src/linux-headers-3.0.0-0300-generic'
  CC [M]  /home/rick/acpi_call/acpi_call.o
  Building modules, stage 2.
  MODPOST 1 modules
  CC      /home/rick/acpi_call/acpi_call.mod.o
  LD [M]  /home/rick/acpi_call/acpi_call.ko
make[1]: Leaving directory`/usr/src/linux-headers-3.0.0-0300-generic'
rick@Abigail:~/acpi_call$ ls
acpi_call.c      acpi_call.mod.o  m11xr2.sh      Module.symvers  test_off.sh
acpi_call.ko     acpi_call.o      Makefile       query_dsdt.pl   windump_hack
acpi_call.mod.c  asus1215n.sh     modules.order  README
rick@Abigail:~/acpi_call$ ./test_off.sh 

This is sitting there for 10 mins now.  The laptop is Acer 5742G with NV optimus and Geforce gt 540M

**Comment by mkottman** [comment]
Actually calling ACPI methods like this project does is black magic, and it surprised me that it worked for me simply like that. Remember that this comes with NO WARRANTY, so if it does nothing for you, or even freezes your computer, simply do not use it. Seems like your laptop has some other way to turn off the GPU.
