### ISSUE TITLE
Lenovo v570 323A-3, Debian sid, onboard intel hd 3000, nvidia gt 525m

### ISSUE THREAD

**Issue by ivankovnatsky** [mkottman/acpi_call#16]
Thanks for that great work, fella!

Well, my thing is module worked for my lenovo only to turn off my discrete card, but can not turn it on back, well that seems to be unsupported:

``` bash
root@lenovo:/home/sevenfourk/sources/git/acpi_call# ./test_off.sh 
Trying \_SB.PCI0.P0P1.VGA._OFF: failed
Trying \_SB.PCI0.P0P2.VGA._OFF: failed
Trying \_SB_.PCI0.OVGA.ATPX: failed
Trying \_SB_.PCI0.OVGA.XTPX: failed
Trying \_SB.PCI0.P0P3.PEGP._OFF: failed
Trying \_SB.PCI0.P0P2.PEGP._OFF: failed
Trying \_SB.PCI0.P0P1.PEGP._OFF: failed
Trying \_SB.PCI0.MXR0.MXM0._OFF: failed
Trying \_SB.PCI0.PEG1.GFX0._OFF: failed
Trying \_SB.PCI0.PEG0.GFX0.DOFF: failed
Trying \_SB.PCI0.PEG1.GFX0.DOFF: failed
Trying \_SB.PCI0.PEG0.PEGP._OFF: works!
```

any suggestions ?

**Comment by mkottman** [comment]
Have you tried running the following? (changing the _OFF to _ON) 

```
echo \_SB.PCI0.PEG0.PEGP._ON > /proc/acpi/call
```

I do not know for sure (I don't have the hardware to test it), but it should work.

**Comment by ivankovnatsky** [comment]
Sorry, for not telling before, yep, I tried that staff as well, still no luck.  I'm not very good in this topic, so I'm gonna read a bit here, anyway this is pretty strange: if my card turns off with that line, why it does not turn on with added "ON" there (I just thought maybe to dig some other lines specs)

**Comment by geser2008** [comment]
I have the same laptop. Everything works great. I'm running Debian Sid with debumblebee. I'm using the same commands: _SB.PCI0.PEG0.PEGP._ON and _SB.PCI0.PEG0.PEGP._OFF. Thanks a lot for your work!

**Comment by ivankovnatsky** [comment]
UPD: Yes it works, thanks
