### ISSUE TITLE
Problems with Kernel 3.2.1

### ISSUE THREAD

**Issue by kozman** [mkottman/acpi_call#24]
Hi,

While using acpi_call with kernel 3.2.1-1, I am unable to suspend/resume my machine. Resulting in a black screen with a cursor and an unresponsive system, a hard reboot being the only way out. 

Sorry I can't be more helpful.
Cheers

(Arch x86-64)

**Comment by Lekensteyn** [comment]
What machine do you have? NVIDIA Optimus machines are supported with a new module: https://github.com/Bumblebee-Project/bbswitch
See also https://wiki.archlinux.org/index.php/Bumblebee
