### ISSUE TITLE
Since Kernel update 3.6.11 acpi_call produces error

### ISSUE THREAD

**Issue by rebootl** [mkottman/acpi_call#30]
kernel: acpi_call: Cannot get handle: Error: AE_NOT_FOUND
repeatadly in journal

It used to work flawlessly before.
Regards

OS:
Arch Linux
Hardware:
HP Pavilion dv6 CORE i5

**Comment by Yutsa** [comment]
I'm using Debian's 3.16 kernel and I also have a lot of "AE_NOT_FOUND" but the GPU is still disabled though, so I guess it still works.
