### ISSUE TITLE
test_off script failed on XPS 17 L701x Intel and Nvidia GeForce 435M

### ISSUE THREAD

**Issue by songtao** [mkottman/acpi_call#5]
Hi 

I am new to ubuntu. please give me some advice.

Trying _SB.PCI0.P0P1.VGA._OFF: failed
Trying _SB.PCI0.P0P2.VGA._OFF: failed
Trying _SB_.PCI0.OVGA.ATPX: failed
Trying _SB_.PCI0.OVGA.XTPX: failed
Trying _SB.PCI0.P0P3.PEGP._OFF: failed
Trying _SB.PCI0.P0P2.PEGP._OFF: failed
Trying _SB.PCI0.P0P1.PEGP._OFF: failed
Trying _SB.PCI0.MXR0.MXM0._OFF: failed
Trying _SB.PCI0.PEG1.GFX0._OFF: failed
Trying _SB.PCI0.PEG0.GFX0.DOFF: failed
Trying _SB.PCI0.PEG1.GFX0.DOFF: failed
Trying _SB.PCI0.PEG0.PEGP._OFF: failed
Trying _SB.PCI0.XVR0.Z01I.DGOF: failed
Trying _SB.PCI0.PEGR.GFX0._OFF: failed
Trying _SB.PCI0.PEG.VID._OFF: failed
Trying _SB.PCI0.PEG0.VID._OFF: failed
Trying _SB.PCI0.P0P2.DGPU._OFF: failed
Trying _SB.PCI0.P0P4.DGPU.DOFF: failed
Trying _SB.PCI0.IXVE.IGPU.DGOF: failed
Trying _SB.PCI0.RP00.VGA._PS3: failed
Trying _SB.PCI0.RP00.VGA.P3MO: failed
Trying _SB.PCI0.GFX0.DSM._T_0: failed
Trying _SB.PCI0.LPC.EC.PUBS._OFF: failed
Trying _SB.PCI0.P0P2.NVID._OFF: failed

**Comment by mkottman** [comment]
Unfortunately, ACPI methods used to turn off the GPU are vendor-specific and undocumented (AFAIK). This list of methods was collected on the [linux hybrid graphics mailing list](http://linux-hybrid-graphics.blogspot.com/). Could you try running [this script](https://lists.launchpad.net/hybrid-graphics-linux/msg00663.html) for Dell XPS 17 (L702X) instead?

**Comment by songtao** [comment]
Thanks for your reply.
I did try run that dellL702 script. Still no luck.

DSM Error: AE_NOT_FOUND
_PS3 Error: AE_NOT_FOUND
Dell L702X Optimus appears to be Error: AE_NOT_FOUND

Here is my system info:
XPS L701X  
A06

00:02.0 VGA compatible controller [0300]: Intel Corporation Core Processor Integrated Graphics Controller [8086:0046](rev 18) (prog-if 00 [VGA controller])
02:00.0 VGA compatible controller [0300]: nVidia Corporation Device [10de:0dd3](rev a1) (prog-if 00 [VGA controller])

I am not sure is this is relative with your project. I really appreciate your help.

Thanks

Songtao
