### ISSUE TITLE
Dell L702X - Step to step

### ISSUE THREAD

**Issue by marste** [mkottman/acpi_call#6]
Hi mkottman, I would need help.
Since I have to go to a friend who has a Dell L702X, I can not take away the computer to test.
The steps to switch from intel to nvidia card with Ubuntu 10.10 are the following?
- sudo apt-get install acpidump iasl
- git clone http://github.com/mkottman/acpi_call.git
- cd acpi_call
- make

Use script that I find here: https://lists.launchpad.net/hybrid-graphics-linux/msg00663.html

Thank you very much in advance

**Comment by avilella** [comment]
Hi,
Have you tried this?
sudo insmod acpi_call.ko
chmod +x dellL702X.sh
./dellL702X.sh off
./dellL702X.sh on

I am ccing to the mailing list: https://lists.launchpad.net/hybrid-graphics-linux/
