### ISSUE TITLE
EEE 1215N All Tests Failed

### ISSUE THREAD

**Issue by mcaltage** [mkottman/acpi_call#7]
I am running an Asus EEE PC 1215N with Ubuntu 11.04.  Installation appeared to work, but the test_off script fails completely.

uname@1215N:~$ git clone http://github.com/mkottman/acpi_call.git
Cloning into acpi_call...
remote: Counting objects: 101, done.
remote: Compressing objects: 100% (57/57), done.
remote: Total 101 (delta 58), reused 76 (delta 42)
Receiving objects: 100% (101/101), 14.97 KiB, done.
Resolving deltas: 100% (58/58), done.
uname@1215N:~$ cd acpi_call
uname@1215N:~/acpi_call$ make
make -C /lib/modules/2.6.38-10-generic-pae/build M=/home/uname/acpi_call modules
make[1]: Entering directory `/usr/src/linux-headers-2.6.38-10-generic-pae'
  CC [M]  /home/uname/acpi_call/acpi_call.o
  Building modules, stage 2.
  MODPOST 1 modules
  CC      /home/uname/acpi_call/acpi_call.mod.o
  LD [M]  /home/uname/acpi_call/acpi_call.ko
make[1]: Leaving directory`/usr/src/linux-headers-2.6.38-10-generic-pae'
uname@1215N:~/acpi_call$ sudo insmod acpi_call.ko
[sudo] password for uname: 
uname@1215N:~/acpi_call$ ./test_off.sh
Trying _SB.PCI0.P0P1.VGA._OFF: failed
Trying _SB.PCI0.P0P2.VGA._OFF: failed
Trying _SB_.PCI0.OVGA.ATPX: failed
Trying _SB_.PCI0.OVGA.XTPX: failed
Trying _SB.PCI0.P0P3.PEGP._OFF: failed
Trying _SB.PCI0.P0P2.PEGP._OFF: failed
Trying _SB.PCI0.P0P1.PEGP._OFF: failed
Trying _SB.PCI0.MXR0.MXM0._OFF: failed
Trying _SB.PCI0.PEG1.GFX0._OFF: failed
Trying _SB.PCI0.PEG0.GFX0.DOFF: failed
Trying _SB.PCI0.PEG1.GFX0.DOFF: failed
Trying _SB.PCI0.PEG0.PEGP._OFF: failed
Trying _SB.PCI0.XVR0.Z01I.DGOF: failed
Trying _SB.PCI0.PEGR.GFX0._OFF: failed
Trying _SB.PCI0.PEG.VID._OFF: failed
Trying _SB.PCI0.PEG0.VID._OFF: failed
Trying _SB.PCI0.P0P2.DGPU._OFF: failed
Trying _SB.PCI0.P0P4.DGPU.DOFF: failed
Trying _SB.PCI0.IXVE.IGPU.DGOF: failed
Trying _SB.PCI0.RP00.VGA._PS3: failed
Trying _SB.PCI0.RP00.VGA.P3MO: failed
Trying _SB.PCI0.GFX0.DSM._T_0: failed
Trying _SB.PCI0.LPC.EC.PUBS._OFF: failed
Trying _SB.PCI0.P0P2.NVID._OFF: failed

**Comment by fff7d1bc** [comment]
for 1215n you have another script, works for me.

**Comment by mcaltage** [comment]
Yes I know, I found it shortly after posting.  It works now.
